model:
  base_learning_rate: 1.0e-4 #5.80e-04
  scale_lr: False
  target: lvdm.models.autoencoder2plus1d_1dcnn.AutoencoderKL2plus1D_1dcnn
  params:
    monitor: "val/rec_loss"
    video_key: video
    image_key: video
    img_video_joint_train: False
    caption_guide: True
    use_quant_conv: False
    t5_model_max_length: 100

    ckpt_path: ckpt/sota-4-16z-text.ckpt
    input_dim: 5
    ignore_keys_3d: ['loss']
    
    lossconfig:
      target: lvdm.modules.losses.LPIPSWithDiscriminator3D
      params:
        disc_start: 50001
        kl_weight: 0
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 16
      resolution: 216
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ] 
      temporal_down_factor: 1
      num_res_blocks: 2
      attn_resolutions: [27, 54, 108, 216]
      dropout: 0.0
    
    ppconfig:
      temporal_scale_factor: 4
      z_channels: 16
      out_ch: 16
      ch: 16 
      attn_temporal_factor: [2,4]
      use_temporal_cross_attention: False
      use_spatial_cross_attention: True