model:
  base_learning_rate: 1.0e-4
  scale_lr: False
  target: src.models.autoencoder2plus1d_1dcnn.AutoencoderKL2plus1D_1dcnn
  params:
    embed_dim: 4
    monitor: "val/rec_loss"
    video_key: video
    image_key: video
    img_video_joint_train: False
    caption_guide: True
    use_quant_conv: True
    t5_model_max_length: 100

    ckpt_path: ckpt/sota-4-4z-text.ckpt
    input_dim: 5

    ignore_keys_3d: ['loss']
    
    lossconfig:
      target: src.modules.losses.LPIPSWithDiscriminator3D
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 216
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ] 
      temporal_down_factor: 1
      num_res_blocks: 2
      attn_resolutions: [27, 54, 108, 216]
      dropout: 0.0
    
    ppconfig:
      temporal_scale_factor: 4
      z_channels: 4
      out_ch: 4
      ch: 4
      attn_temporal_factor: [2,4]

data:
  target: data.lightning_data.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 32
    wrap: false
    train:
      target: data.dataset.DatasetVideoLoader
      params:
        csv_file: path/to/your.csv
        resolution: [216, 216]
        video_length: 16
        subset_split: train
    validation:
      target: data.dataset.DatasetVideoLoader
      params:
        csv_file: path/to/your.csv
        resolution: [216, 216]
        video_length: 16
        subset_split: val

lightning:
  find_unused_parameters: True
  callbacks:
    image_logger:
      target: utils.callbacks.ImageLogger
      params:
        batch_frequency: 509
        max_images: 8
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: '{epoch:06}-{step:09}'
        save_weights_only: True
        every_n_train_steps: 5000
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    batch_size: 1
    num_workers: 32
    max_epochs: 3000
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_train_steps: 3000
      filename: "{epoch:04}-{step:06}"